openapi: 3.0.0
info:
  title: Fruitable API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8000/api/v1
    description: local server.
  - url: http://.example.com
    description: Optional server description, e.g. Internal staging server for testing
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []              
paths:
  /users/register:
    post:
      summary: User Register.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - users
      requestBody:
        required: true
        content:
           multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                role:
                  type: string
                password:
                  type: string
                avtar:
                  type: string
                  format: binary
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string          
  /users/login:
    post:
      summary: User Login.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - users
      requestBody:
        required: true
        content:
           application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/logout:
    post:
      summary: User Logout.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - users
      requestBody:
        required: true
        content:
           application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/generateNewTokens:
    post:
      summary: Creat mew accsess and refresh Token.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - users
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/googlelogin:
    get:
      summary: user google Login browser.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - users
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /categories/list-categories:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: pageSize
          schema:
            type: integer
          description: The numbers of items to return
      summary: list Categories.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - categories
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /categories/update-category/{category_id}:
    put:
      summary: update Register.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - categories
      parameters:
        - in: path
          name: category_id
          schema:
            type: string
          required: true
          description: Update category.
      requestBody:
        required: true
        content:
           application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
               

                  
  